export const langvars = {
    accessibility: "Accessibility",
    additional_notes: "Additional instructions",
    agreement: "By confirming, you agree to our",
    allergy_free: "Allergy free",
    available_slots: "Here are the available time slots for",
    baby_chair: "Baby chair",
    bday: "Birthday",
    book_appointment: "Book an appointment",
    book_table: "Book a table",
    buy_voucher: "Buy Boncado vouchers",
    by_email: "By e-mail",
    by_post: "By post mail",
    category_consultation: "Consultation",
    category_label: "Category",
    category_select: "Select a category",
    check_availability: "Check availability",
    checkout: "Checkout",
    choose_hour: "Time to dig in—what's your ideal hour?",
    color: "Color",
    city_zip: "City, post code",
    complete_order: "Complete order",
    confirm: "Yes, I confirm",
    confirmation_msg: "Your booking is confirmed! Please check your email for the details. See you soon!",
    day_select: "Choose your ideal dining day",
    fast_meal: "Fast meal",
    filter_prompt: "What are you looking for?",
    filter: "Filter",
    final_confirm: "Confirm my booking",
    grab_seat: "Grab a seat!",
    guest_count: "How many guests?",
    guest_label: "Guest/s",
    i_would_like: "I would like ...",
    identity_prompt: "Just share your name, email, and phone, and we’ll handle the rest!",
    leisure_meal: "Leisure meal",
    message: "Message",
    mood: "Set the vibe",
    motivation: "Your next great meal is justa booking away!",
    other: "Other",
    patio: "Patio",
    payment_card: "Debit or Credit card",
    payment_method_prompt: "Pick your preferred way to pay",
    payment_secure: "Your payment is secure with",
    pet_friendly: "Pet friendly",
    place_order: "Place order",
    planify: "Planify",
    proceed: "Proceed",
    product_description: "Description",
    product_total_note: "The total, including <strong>shipping and tax</strong>, will be calculated on the next step.",
    professional_meal: "Professional meal",
    purchase_products: "Purchase products",
    quantity: "Quantity",
    quick_details: "Just a few quick details",
    ready: "All set",
    redirect_notice: "Once you choose, we’ll redirect you to complete the details.",
    required_field: "Mandatory",
    review_prompt: "Take a moment to review your info before we confirm your reservation.",
    save_spot: "Save my spot",
    scheduled_by: "Scheduled by",
    select_all: "Select all items",
    set_time: "Set the clock",
    shipping_fee: "Shipping Fee",
    size: "Size",
    special_event: "Special event",
    ssl_notice: "SSL encryption.",
    step_choose: "Choose your appointment and set a date.",
    step_identity: "Just share your name, email, and phone, and we’ll handle the rest!",
    step_review: "Take a moment to review your info before we confirm your reservation.",
    step_when: "When’s a good time for you?",
    stroller: "Stroller",
    subtotal: "Subtotal",
    success: "Success!",
    tax: "Tax",
    terms: "Terms & Conditions",
    time_slot: "Time slot",
    total: "Total",
    type_prompt: "Business, casual, celebration, or a quick bite—tell us what’s on the menu!",
    uncover_hidden_gems: "Uncover hidden gems – let’s shop!",
    under_name: "For reservation under",
    variant: "Variant",
    voucher_add_details: "Add the details",
    voucher_cc_email: "For extra peace of mind, you might want to send a copy of the Boncado to another email address, too",
    voucher_contact: "Phone or email",
    voucher_delivery_choice: "How would you like them to receive the Boncado?",
    voucher_delivery_detail_prompt: "Just a few details to send your gift—how should we deliver?",
    voucher_delivery_options: "Choose whether to deliver your gift by mail, SMS, or email—easy, fast, and full of surprises!",
    voucher_delivery_planning: "We'll email or text the Boncado on your chosen date. You can print it yourself or send it directly to the recipient and even schedule the sending date.",
    voucher_emotion: "Because nothing says ‘I care’ like the freedom to choose—and a little surprise!",
    voucher_finalize: "Complete your purchase and get ready to spread some serious smiles!",
    voucher_from: "From",
    voucher_intro: "Unlock happiness with these gift vouchers!",
    voucher_personal_note: "Let’s make it personal—tell us who’s getting the love!",
    voucher_personalize: "Add a personal touch—tell us who it's for, how much happinessto send, and your personal message!",
    voucher_post_description: "We'll send you a high-definition printed Boncado, delicately encased in a charming cardboard sleeve, for just <span class=\"fw-bold\">€2.99 extra per voucher.</span>",
    voucher_recipient_address: "Address",
    voucher_recipient_fullname: "Full name",
    voucher_recipient_label: "Who is it for?",
    voucher_send_someone: "Make someone happy and send them a voucher!",
    voucher_special_touch: "Make it extra special!",
    voucher_spread_joy: "How do you want tospread the joy?",
    voucher_to: "To",
    your_cart_awaits: "Your cart awaits",
    what_your_pmeal_plan: "What's Your Meal Plan?",
    what_your_pmeal_plan_desc: "Business, casual, celebration, or a quick bite—tell us what’s on the menu!",
    almost_there: "Almost there!",
    reservation_details: "Reservation details",
    make_appointment: "Make an appointment",
    choose_time: "Choose your time!",
    are_correct: "Are these correct?",
    thank_you: "Thank you",
    seal_the_deal: "Almost there—time toseal the deal!",
    voucher_click_preview: "Click to flip the voucher",
    value: "Value",
    back: "Back",
    in_rush: "In rush",
    what_vibe: "What’s the vibe?",
    first_name: "First name",
    last_name: "Last name",
    email: "Email",
    phone: "Phone",
    confirm: "Confirm",
    add_to_cart: "Add to cart",
    delete_selected: "Delete selected",
    select_category: "Select a category",
    select_option: "Select an option",
    shipping_standard: "Standard (3–5 business days)",
    shipping_express: "Express (1–2 business days)",
    shipping_pickup: "Pickup",
    browse_vouchers: "Browse for more voucher designs.",
    purchase_another_voucher: "Purchase another voucher",
    make_extra_special: "Make it extra special!",
    payment_confirmation: "Payment confirmation",
    error: "Error",
    suggestion_title: "Suggestion title",
    selected_suggestion: "Selected suggestion",
    edit: "Edit",
    delete: "Delete",
    fullname: "Full name",
    plan: "Date",
    email_or_tel: "Email or Telephone",
    secondary_email: "Secondary email",
    payment_in_progress: "Payment in progress",
    waiting_payment_confirmation: "Waiting for payment confirmation.",
    order_help: "Order help",
    payment_details: "Payment details",
    billing_information: "Billing information",
    i_want_invoice: "I want an invoice",
    company: "Company",
    company_number: "Business #",
    address: "Address",
    postal_code: "Postal code",
    city: "City",
    country: "Country",
    delivery_cost: "Delivery costs",
    complete_purchase_prompt: "Complete your purchase by providing your payment information.",
    voucher_custom_amount_title: "Custom amount",
    voucher_custom_amount_desc: "Choose a custom amount to make your gift more personal and meaningful.",
    voucher_custom_amount_cta: "Set custom amount",
    next: "Next",
    email_planify_helper: "Do not specify a date if you would like the Boncado(s) to be sent immediately after payment.",
    no_subscription: "No Active Subscription...",
    all_slots_passed: "All slots are in the past.",
    no_available_slots_week: "No available slots within this week.",
    go_to_available_week: "Go to next available week",
    deposit_required: "Deposit required",
    pay_deposit_of: "Pay a deposit of",
    delivery_house_number: "House number",
    delivery_street: "Street",
    delete_cart_items: "Delete all selected products?",
    delete_warning: "This action cannot be undone.",
    cancel: "Cancel",
    no_items_selected: "No items selected",
    no_items_selected_message: "Please select at least one item in your cart to proceed.",
    buy_now: "Buy now",
    continue_shopping: "Continue shopping",
    shipping_information: "Shipping information",
    billing_information: "Billing information",
    same_shipping_billing_information: "Use shipping information as biling information",
    added_to_cart: "Item has been added to your shopping cart",
    check: "Chèque",
    deliver_to: "Deliver to",
    shipping_method: "Shipping method",
    new: "New",
    best_seller: "Best seller",
    cart_empty: "Cart is empty",
    house_number: "House no.",
    street: "Street",
    purchase_another_product: "Purchase another product.",
    book_another_appointment: "Book another appointment.",
    book_another_table: "Book another table.",
    total_articles: "Total articles",
    including_tax: "incl. {amount}€ taxes (VAT)",
    confirmation_msg_agenda: "Your booking is confirmed! Please check your email for the details. See you soon!",
    confirmation_msg_voucher: "Your gift voucher has been successfully purchased! Please check your email for the details. Thank you!",
    confirmation_msg_ecommerce: "Your order is confirmed! Please check your email for the details. Thank you!",
    confirmation_msg_table: "Your table reservation is confirmed! Please check your email for the details. See you soon!",
    more: "More",
    majoration_eligible: "You are eligible for the bonus!",
    majoration_you_pay: "You pay",
    majoration_worth: "voucher worth",
    majoration_qty_remaining: "{qty} bonus(es) remaining for you.",
    majoration_accept: "Yes, I want to use it",
    majoration_decline: "No, not this time",
    majoration: "Majoration",
    majoration_voucher_worth: "Voucher worth",
    majoration_email_title: "Confirm your email",
    majoration_email_desc: "Enter your email address to validate the bonus.",
    majoration_email_invalid: "Please enter a valid email address.",
    majoration_email_confirmed_message: "Your bonus has been successfully applied to your voucher.",
    majoration_accepted_message: "You have chosen to take advantage of the bonus.",
    majoration_cancel_decision: "Cancel this decision",
    majoration_min_notice: "This offer only applies to vouchers with a minimum value of {min}.",
    majoration_declined_message: "An increase is possible, but you have chosen not to take advantage of it this time.",
    reset: "Reset",
    majoration_partial: "Bonus applied to {n} out of {total} voucher(s).",
};