export const langvars = {
    accessibility: "Accessibilité",
    additional_notes: "Instructions supplémentaires",
    agreement: "En confirmant, vous acceptez nos",
    allergy_free: "Sans allergènes",
    available_slots: "Voici les créneaux disponibles pour",
    baby_chair: "Chaise bébé",
    bday: "Anniversaire",
    book_appointment: "Prendre rendez-vous",
    book_table: "Réserver une table",
    buy_voucher: "Acheter un chèque-cadeau",
    by_email: "Par e-mail / SMS",
    by_post: "Par courrier postal",
    category_consultation: "Consultation",
    category_label: "Catégorie",
    category_select: "Sélectionnez une catégorie",
    check_availability: "Vérifier les disponibilités",
    checkout: "Vers le paiement",
    choose_hour: "C’est l’heure de manger — quelle est votre heure idéale ?",
    color: "Couleur",
    city_zip: "Ville, code postal",
    complete_order: "Finaliser la commande",
    confirm: "Oui, je confirme",
    confirmation_msg: "Votre réservation est confirmée ! Veuillez vérifier votre e-mail pour les détails. À bientôt !",
    day_select: "Choisissez votre jour de repas idéal",
    fast_meal: "Repas rapide",
    filter_prompt: "Que recherchez-vous ?",
    filter: "Filtrer",
    final_confirm: "Confirmer ma réservation",
    grab_seat: "Prenez un siège!",
    guest_count: "Combien d'invités ?",
    guest_label: "Invité(s)",
    i_would_like: "Je souhaiterais...",
    identity_prompt: "Partagez simplement votre nom, votre e-mail et votre téléphone, et nous nous occupons du reste !",
    leisure_meal: "Repas détente",
    message: "Message",
    mood: "Choisissez l'ambiance",
    motivation: "Votre prochain bon moment est àune réservation près !",
    other: "Autre",
    patio: "Terrasse",
    payment_card: "Carte de débit ou crédit",
    payment_method_prompt: "Choisissez votre méthode de paiement préférée",
    payment_secure: "Votre paiement est sécurisé avec",
    pet_friendly: "Animaux admis",
    place_order: "Passer la commande",
    planify: "Planifier",
    proceed: "Continuer",
    product_description: "Description",
    product_total_note: "Le total, incluant <strong>les frais de livraison et la TVA</strong>, sera calculé à l’étape suivante.",
    professional_meal: "Repas professionnel",
    purchase_products: "Acheter des produits",
    quantity: "Quantité",
    quick_details: "Quelques détails rapides",
    ready: "Tout est prêt",
    redirect_notice: "Une fois votre choix effectué, vous serez redirigé pour compléter les détails.",
    required_field: "Champ obligatoire",
    review_prompt: "Prenez un moment pour vérifier vos informations avant de confirmer votre réservation.",
    save_spot: "Réserver ce créneau",
    scheduled_by: "Planifié par",
    select_all: "Tout sélectionner",
    set_time: "Définir l’heure",
    shipping_fee: "Frais de livraison",
    size: "Taille",
    special_event: "Événement spécial",
    ssl_notice: "Chiffrement SSL.",
    step_choose: "Choisissez votre rendez-vous et fixez une date.",
    step_identity: "Partagez simplement votre nom, votre e-mail et votre téléphone, et nous nous occupons du reste !",
    step_review: "Prenez un moment pour vérifier vos informations avant que nous confirmions votre réservation.",
    step_when: "Quel moment vous conviendrait ?",
    stroller: "Poussette",
    subtotal: "Sous-total",
    success: "Succès !",
    tax: "TVA",
    terms: "Conditions générales",
    time_slot: "Créneau horaire",
    total: "Total",
    type_prompt: "Affaires, détente, célébration ou pause rapide — dites-nous ce qui vous amène !",
    uncover_hidden_gems: "Achetez en quelques clics",
    under_name: "Réservation au nom de",
    variant: "Variante",
    voucher_add_details: "Ajouter les détails",
    voucher_cc_email: "Pour plus de tranquillité, vous pouvez envoyer une copie du Boncado à une autre adresse e-mail",
    voucher_contact: "Téléphone ou e-mail",
    voucher_delivery_choice: "Comment souhaitez-vous que le Boncado soit reçu ?",
    voucher_delivery_detail_prompt: "Quelques détails pour l’envoi du cadeau — comment devons-nous procéder ?",
    voucher_delivery_options: "Par sms, par email ? Par courrier postal pour y mettre la forme ?",
    voucher_delivery_planning: "Nous enverrons le Boncado par e-mail ou SMS à la date choisie. Vous pouvez aussi l’imprimer ou planifier l’envoi.",
    voucher_emotion: "Une valeur libre ou une petite suggestion sans engagement...",
    voucher_finalize: "Finalisez votre achat et préparez-vous à faire sourire !",
    voucher_from: "De la part de",
    voucher_intro: "Offrez du bonheur avec Boncado !",
    voucher_personal_note: "Ajoutez une touche personnelle — dites-nous qui reçoit ce Boncado !",
    voucher_personalize: "Indiquez à qui c’est destiné, le montant du bonheur à offrir et votre message !",
    voucher_post_description: "Nous vous enverrons un Boncado imprimé en haute définition, soigneusement emballé dans une pochette cartonnée, pour seulement <span class=\"fw-bold\">2,99 € de plus par Boncado.</span>",
    voucher_recipient_address: "Adresse",
    voucher_recipient_fullname: "Nom complet",
    voucher_recipient_label: "Pour qui est-ce ?",
    voucher_send_someone: "Faites plaisir à quelqu’un en lui envoyant un Boncado !",
    voucher_special_touch: "Rendez-le encore plus spécial !",
    voucher_spread_joy: "Comment souhaitez-vous que le Boncado soit reçu ?",
    voucher_to: "À",
    your_cart_awaits: "Votre panier vous attend",
    what_your_pmeal_plan: "Quel est votre type de repas ?",
    what_your_pmeal_plan_desc: "Affaires, détente, célébration ou pause rapide — dites-nous ce que vous prévoyez !",
    almost_there: "Presque terminé !",
    reservation_details: "Détails de la réservation",
    make_appointment: "Prendre un rendez-vous",
    choose_time: "Choisissez votre heure !",
    are_correct: "Est-ce correct ?",
    thank_you: "Merci",
    seal_the_deal: "Presque fini — il est temps de finaliser !",
    voucher_click_preview: "Cliquez pour retourner le Boncado",
    value: "Valeur",
    back: "Retour",
    in_rush: "Pressé",
    what_vibe: "Quel est le contexte ?",
    first_name: "Prénom",
    last_name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    confirm: "Confirmer",
    add_to_cart: "Ajouter au panier",
    delete_selected: "Supprimer la sélection",
    select_category: "Sélectionner une catégorie",
    select_option: "Sélectionner une option",
    shipping_standard: "Standard (3–5 business days)",
    shipping_express: "Express (1–2 business days)",
    shipping_pickup: "Enlèvement au magasin",
    browse_vouchers: "Choisir un autre visuel",
    purchase_another_voucher: "Acheter un autre chèque-cadeau",
    make_extra_special: "Sélectionner la touche graphique qui fait la différence !",
    payment_confirmation: "Payment confirmation",
    error: "Erreur",
    suggestion_title: "Suggestion title",
    selected_suggestion: "Suggestion sélectionnée",
    edit: "Modifier",
    delete: "Supprimer",
    fullname: "Nom complet",
    plan: "Date",
    email_or_tel: "Email ou téléphone",
    secondary_email: "Email de sécurité",
    payment_in_progress: "Chargement de la page de paiement",
    waiting_payment_confirmation: "En attente de la confirmation de paiement",
    order_help: "Aide",
    payment_details: "Détails du paiement",
    billing_information: "Données de facturation",
    i_want_invoice: "Je désire une facture",
    company: "Entreprise",
    company_number: "N° de TVA",
    address: "Adresse",
    postal_code: "Code postal",
    city: "Localité",
    country: "Pays",
    delivery_cost: "Livraison",
    complete_purchase_prompt: "Finalisez votre achat en complétant les informations de paiement",
    voucher_custom_amount_title: "Un chèque avec une valeur libre",
    voucher_custom_amount_desc: "Offrez un chèque de la valeur de votre choix",
    voucher_custom_amount_cta: "Suivant",
    next: "Suivant",
    email_planify_helper: "N'indiquez pas de date si vous désirez que le(s) Boncado soit/soient envoyé(s) immédiatement après le paiement",
    no_subscription: "Aucun module actif dans votre abonnement...",
    all_slots_passed: "Toutes les disponibilités sont passées",
    no_available_slots_week: "Pas de disponibilité pour cette semaine",
    go_to_available_week: "Aller à la première disponibilité",
    deposit_required: "Acompte requis",
    pay_deposit_of: "Payer un acompte de",
    delivery_house_number: "N°",
    delivery_street: "Rue",
    delete_cart_items: "Voulez retirer tous les produits sélectionnés",
    delete_warning: "Cette action est irréversible.",
    cancel: "Annuler",
    no_items_selected: "No items selected",
    no_items_selected_message: "Please select at least one item in your cart to proceed.",
    buy_now: "Acheter maintenant",
    continue_shopping: "Continuer le shopping",
    shipping_information: "Coordonnées de livraison",
    billing_information: "Coordonnées de facturation",
    same_shipping_billing_information: "L'adresse de facturation est la même que celle de livraison",
    added_to_cart: "L'article a été ajouté à votre panier",
    check: "Chèque",
    deliver_to: "Livré à",
    shipping_method: "Mode de livraison",
    new: "New",
    best_seller: "Best seller",
    cart_empty: "Le panier est vide",
    house_number: "N°",
    street: "Rue",
    purchase_another_product: "Acheter un autre produit.",
    book_another_appointment: "Passer une nouvelle réservation.",
    book_another_table: "Book another table.",
    total_articles: "Total des articles",
    including_tax: "dont {amount}€ de taxes (tva)",
    confirmation_msg_agenda: "Votre réservation est confirmée ! Veuillez consulter votre boîte mail pour plus de détails. À bientôt !",
    confirmation_msg_voucher: "Votre chèque-cadeau Boncado a bien été acheté ! Veuillez consulter votre boîte mail pour plus de détails. Merci !",
    confirmation_msg_ecommerce: "Votre commande est confirmée ! Veuillez consulter votre boîte mail pour plus de détails. Merci !",
    confirmation_msg_table: "Votre réservation est confirmée ! Veuillez consulter votre boîte mail pour plus de détails. À bientôt !",
    more: "more",
    majoration_eligible: "You are eligible for the bonus!",
    majoration_you_pay: "You pay",
    majoration_worth: "voucher worth",
    majoration_qty_remaining: "{qty} bonus(es) remaining for you.",
    majoration_accept: "Yes, I want to use it",
    majoration_decline: "No, not this time",
    majoration: "Majoration",
    majoration_voucher_worth: "Voucher worth",
    majoration_email_title: "Confirm your email",
    majoration_email_desc: "Indiquez votre adresse email afin de vérifier si vous êtes éligible à cette offre.",
    majoration_email_invalid: "Veuillez indiquer une adresse email valide.",
    majoration_email_confirmed_message: "Your bonus has been successfully applied to your voucher.",
    majoration_accepted_message: "Vous avez accepté la proposition dez majoration",
    majoration_cancel_decision: "Annuler",
    majoration_min_notice: "Cette offre de majoration s'applique uniquement sur les chèques-cadeaux d'une valeur minimale de {min}.",
    majoration_declined_message: "Une majoration est possible mais vous avez choisi de ne pas en profiter cette fois-ci.",
    reset: "Je change d'avis",
    majoration_partial: "Bonus applied to {n} out of {total} voucher(s).",
};


